# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='content',
        ),
    ]
